const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('desktop', {
  getStatus: () => ipcRenderer.invoke('app:status'),
  connect: () => ipcRenderer.invoke('app:connect'),
  reconnect: () => ipcRenderer.invoke('app:reconnect'),
  chooseWorkspace: () => ipcRenderer.invoke('workspace:choose'),
  getWorkspace: () => ipcRenderer.invoke('workspace:get'),
  listWorkspaces: () => ipcRenderer.invoke('workspace:list'),
  listSessions: () => ipcRenderer.invoke('session:list'),
  createSession: () => ipcRenderer.invoke('session:create'),
  getSessionHistory: (sessionId) => ipcRenderer.invoke('session:history', sessionId),
  getSessionModels: (sessionId) => ipcRenderer.invoke('session:models', sessionId),
  selectSessionModel: (selection) => ipcRenderer.invoke('session:select-model', selection),
  promptSession: (sessionId, text) => ipcRenderer.invoke('session:prompt', { sessionId, text }),
  cancelSession: (sessionId) => ipcRenderer.invoke('session:cancel', sessionId),
  getProvider: () => ipcRenderer.invoke('provider:get'),
  getUsage: () => ipcRenderer.invoke('usage:get'),
  discoverProviderModels: (config) => ipcRenderer.invoke('provider:discover-models', config),
  saveProvider: (config) => ipcRenderer.invoke('provider:save', config),
  removeProvider: (provider) => ipcRenderer.invoke('provider:remove', provider),
  listCredentials: () => ipcRenderer.invoke('credentials:list'),
  openSignIn: (url) => ipcRenderer.invoke('auth:open', url),
  listAuthorizations: () => ipcRenderer.invoke('authorization:list'),
  beginAuthorization: (request) => ipcRenderer.invoke('authorization:begin', request),
  answerAuthorization: (request) => ipcRenderer.invoke('authorization:answer', request),
  cancelAuthorization: (request) => ipcRenderer.invoke('authorization:cancel', request),
  clearCredential: (ref) => ipcRenderer.invoke('credentials:clear', ref),
  receivePlugin: () => ipcRenderer.invoke('plugin:receive'),
  activatePlugin: (id) => ipcRenderer.invoke('plugin:activate', id),
  disablePlugin: (name) => ipcRenderer.invoke('plugin:disable', name),
  rollbackPlugin: () => ipcRenderer.invoke('plugin:rollback'),
  listProviders: () => ipcRenderer.invoke('llm:providers'),
  listPlugins: () => ipcRenderer.invoke('plugin:list'),
  restoreHarnessCore: () => ipcRenderer.invoke('harness:restore-core'),
  testApi: (config) => ipcRenderer.invoke('api:test', config),
  savePluginGuide: () => ipcRenderer.invoke('plugin:guide'),
  saveStarterPlugin: () => ipcRenderer.invoke('plugin:starter'),
  minimizeWindow: () => ipcRenderer.invoke('window:minimize'),
  maximizeWindow: () => ipcRenderer.invoke('window:maximize'),
  closeWindow: () => ipcRenderer.invoke('window:close'),
  setWorkspace: (target) => ipcRenderer.invoke('workspace:set', target),
  listWorkspaceFiles: () => ipcRenderer.invoke('workspace:files'),
  readWorkspaceFile: (target) => ipcRenderer.invoke('workspace:readFile', target),
  saveWorkspaceFile: (target, text) => ipcRenderer.invoke('workspace:saveFile', { path: target, text }),
  listArtifacts: () => ipcRenderer.invoke('artifacts:list'),
  listSkills: () => ipcRenderer.invoke('skills:list'),
  createSkill: (input) => ipcRenderer.invoke('skills:create', input),
  readFile: (target) => ipcRenderer.invoke('files:read', target),
  previewFile: (target) => ipcRenderer.invoke('files:preview', target),
  openFile: (target) => ipcRenderer.invoke('files:open', target),
  revealFile: (target) => ipcRenderer.invoke('files:reveal', target),
  getLogs: () => ipcRenderer.invoke('logs:get'),
  reportLog: (source, message) => ipcRenderer.send('log:renderer', source, message),
  relaunch: () => ipcRenderer.invoke('app:relaunch'),
  onLog: (callback) => ipcRenderer.on('log:line', (_event, line) => callback(line)),
  onHarnessStatus: (callback) => ipcRenderer.on('harness:status', (_event, status) => callback(status)),
  onEngineEvent: (callback) => ipcRenderer.on('engine:event', (_event, message) => callback(message)),
});
